### ISSUE TITLE
Django configuration install error

### ISSUE THREAD

**Issue by fleimgruber** [Forum-Informationsfreiheit/OffenesParlament#19]
I followed the instructions up to `vagrant up`. The system packages installation looks good, but during the pip install steps I get the error

```
==> offenesparlament: Obtaining django-configurations-head from git+https://github.com/jezdez/django-configurations.git@5ece107044#egg=django-configurations-head (from -r requirements.txt (line 30))
==> offenesparlament:   Directory /vagrant/src/django-configurations-head already exists, and is not a git clone.
==> offenesparlament:   The plan is to install the git repository https://github.com/jezdez/django-configurations.git
==> offenesparlament: Exception:
==> offenesparlament: Traceback (most recent call last):
==> offenesparlament:   File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 211, in main
==> offenesparlament:     status = self.run(options, args)
==> offenesparlament:   File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 294, in run
==> offenesparlament:     requirement_set.prepare_files(finder)
==> offenesparlament:   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 334, in prepare_files
==> offenesparlament:     functools.partial(self._prepare_file, finder))
==> offenesparlament:   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
==> offenesparlament:     more_reqs = handler(req_to_install)
==> offenesparlament:   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 433, in _prepare_file
==> offenesparlament:     req_to_install.update_editable(not self.is_download)
==> offenesparlament:   File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 573, in update_editable
==> offenesparlament:     vcs_backend.obtain(self.source_dir)
==> offenesparlament:   File "/usr/local/lib/python2.7/dist-packages/pip/vcs/git.py", line 109, in obtain
==> offenesparlament:     if self.check_destination(dest, url, rev_options, rev_display):
==> offenesparlament:   File "/usr/local/lib/python2.7/dist-packages/pip/vcs/__init__.py", line 241, in check_destination
==> offenesparlament:     prompt[1])
==> offenesparlament:   File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 135, in ask_path_exists
==> offenesparlament:     return ask(message, options)
==> offenesparlament:   File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 146, in ask
==> offenesparlament:     response = input(message)
==> offenesparlament: EOFError: EOF when reading a line
==> offenesparlament: What to do?  (i)gnore, (w)ipe, (b)ackup Your response ('exit') was not one of the expected responses: i, w, b
```

which later leads to this

```
==> offenesparlament: Successfully installed Django-1.8.6 Jinja2-2.8 MarkupSafe-0.23 Pygments-2.0.2 alabaster-0.7.6 babel-2.1.1 django-debug-toolbar-1.4 django-debug-toolbar-template-timings-0.6.4 docutils-0.12 pytz-2015.7 six-1.10.0 snowballstemmer-1.2.0 sphinx-1.3.1 sphinx-rtd-theme-0.1.9 sqlparse-0.1.18
==> offenesparlament: Traceback (most recent call last):
==> offenesparlament:   File "manage.py", line 21, in <module>
==> offenesparlament:     
==> offenesparlament: run()
==> offenesparlament:   File "manage.py", line 13, in run
==> offenesparlament:     
==> offenesparlament: from configurations.management import execute_from_command_line
==> offenesparlament: ImportError
==> offenesparlament: : No module named configurations.management
==> offenesparlament: Traceback (most recent call last):
==> offenesparlament:   File "manage.py", line 21, in <module>
==> offenesparlament:     
==> offenesparlament: run()
==> offenesparlament:   File "manage.py", line 13, in run
==> offenesparlament:     
==> offenesparlament: from configurations.management import execute_from_command_line
==> offenesparlament: ImportError
==> offenesparlament: : 
==> offenesparlament: No module named configurations.management
==> offenesparlament: Traceback (most recent call last):
==> offenesparlament:   File "./manage.py", line 21, in <module>
==> offenesparlament:     
==> offenesparlament: run()
==> offenesparlament:   File "./manage.py", line 13, in run
==> offenesparlament:     
==> offenesparlament: from configurations.management import execute_from_command_line
==> offenesparlament: ImportError
==> offenesparlament: : 
==> offenesparlament: No module named configurations.management
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Any ideas on what could be going wrong?

**Comment by lyrixderaven** [comment]
Hej, 

that was a problem with a wrongly added directory (the src directory wasn't supposed to be in GIT, actually). I removed it, if you pull and try again, it should work now! Thanks for the hint :-)

**Comment by fleimgruber** [comment]
Works.
