### ISSUE TITLE
Distribute issues

### ISSUE THREAD

**Issue by fin** [Forum-Informationsfreiheit/OffenesParlament#32]
bootstrap.sh fails - apparently in one of the "pip install" stages, with:

  No module named pkg_resources

**Comment by lyrixderaven** [comment]
... goddammit. worked for me - i did a fresh install yesterday! can you troubleshoot it on your vagrant machine?

**Comment by fin** [comment]
yes, fixed it locally, but it seemed like it happened to other people too…

**Comment by lyrixderaven** [comment]
ok. can you work the fix into the bootstrap.sh provisioner then? if not, i'll need to know what you did to fix it (and preferrably the complete stacktrace - No module named pkg_resources is kind of a generic python-ish problem that can happen due to a million reasons...).

**Comment by fin** [comment]
the error happened on `pip install -r requirements.txt` after a `vagrant destroy && vagrant up`

```
 ==> offenesparlament: Traceback (most recent call last):
 ==> offenesparlament:   File "/usr/local/bin/pip", line 5, in <module>
 ==> offenesparlament:
 ==> offenesparlament: from pkg_resources import load_entry_point
 ==> offenesparlament: ImportError
 ==> offenesparlament: :
 ==> offenesparlament: No module named pkg_resources
 ==> offenesparlament: Traceback (most recent call last):
 ==> offenesparlament:   File "/usr/local/bin/pip", line 5, in <module>
 ==> offenesparlament:
 ==> offenesparlament: from pkg_resources import load_entry_point
 ==> offenesparlament: ImportError
 ==> offenesparlament: :
 ==> offenesparlament: No module named pkg_resources
```

what i did was

```
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | sudo python
```

as suggested by https://stackoverflow.com/questions/18981261/python-easy-install-stops-working-after-distribute-upgrade

i'm not sure if we want this in the bootstrap file, however

**Comment by fin** [comment]
so `vagrant up` still fails (after `vagrant destroy` on osx)…

```
==> offenesparlament: sudo
==> offenesparlament: :
==> offenesparlament: supervisord: command not found
==> offenesparlament: W
==> offenesparlament: :
==> offenesparlament: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/precise/InRelease
==> offenesparlament: W
==> offenesparlament: :
==> offenesparlament: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/precise-updates/InRelease
==> offenesparlament: W
==> offenesparlament: :
==> offenesparlament: Failed to fetch http://security.ubuntu.com/ubuntu/dists/precise-security/InRelease
==> offenesparlament: W
==> offenesparlament: : Failed to fetch http://packages.elastic.co/elasticsearch/1.6/debian/dists/stable/InRelease
==> offenesparlament:
==> offenesparlament: W: Failed to fetch http://packages.elastic.co/elasticsearch/1.6/debian/dists/stable/Release.gpg  Temporary failure resolving 'packages.elastic.co'
==> offenesparlament:
==> offenesparlament: W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/precise-security/Release.gpg  Temporary failure resolving 'security.ubuntu.com'
==> offenesparlament:
==> offenesparlament: W: Some index files failed to download. They have been ignored, or old ones used instead.
```

```

==> offenesparlament: nstallation: distribute 0.6.24dev-r0
==> offenesparlament:     Uninstalling distribute:
==> offenesparlament:       Successfully uninstalled distribute
==> offenesparlament:   Running setup.py install for distribute
==> offenesparlament:
==> offenesparlament:   Running setup.py install for pycparser
==> offenesparlament:     Traceback (most recent call last):
==> offenesparlament:       File "<string>", line 1, in <module>
==> offenesparlament:     ImportError: No module named setuptools
==> offenesparlament:     Complete output from command /usr/bin/python -c "import setuptools;__file__='/vagrant/build/pycparser/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-LVbRrT-record/install-record.txt:
==> offenesparlament:     Traceback (most recent call last):
==> offenesparlament:
==> offenesparlament:   File "<string>", line 1, in <module>
==> offenesparlament:
==> offenesparlament: ImportError: No module named setuptools
==> offenesparlament:
==> offenesparlament: ----------------------------------------
==> offenesparlament: Command /usr/bin/python -c "import setuptools;__file__='/vagrant/build/pycparser/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-LVbRrT-record/install-record.txt failed with error code 1
==> offenesparlament: Storing complete log in /home/vagrant/.pip/pip.log
==> offenesparlament: Traceback (most recent call last):
==> offenesparlament:   File "/usr/bin/pip", line 5, in <module>
==> offenesparlament:
==> offenesparlament: from pkg_resources import load_entry_point
==> offenesparlament: ImportError
==> offenesparlament: :
==> offenesparlament: No module named pkg_resources
```

```

TASK: [Drop local postgresdb] *************************************************
failed: [offenesparlament] => {"failed": true}
msg: the python psycopg2 module is required

FATAL: all hosts have already failed -- aborting
```

**Comment by lyrixderaven** [comment]
output looks like the internet connection to the apt-repos was (temporarily) lost. shoddy network while running vagrant up maybe? then, of course, it will fail, b/c it can’t get the dependencies it needs for the python stuff we need.

you’re on the latest revision? ben added some fixes last week, too. this is _very_ strange. works and worked for me without a hitch. i’ll try once more, but if i can’t replicate your issues, i can’t debug it. pls bring your macbook tonight so i can see for myself maybe and work out a fix for the future?

**Comment by fin** [comment]
yes. same distribute issue, fixed by

`wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | sudo python`

should we create a local copy of this and just execute it before `pip install -r requirements.txt`?

**Comment by fin** [comment]
i was on the wrong branch, this has been fixed in HEAD.
sorry!
